/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWardrobeRouteImport } from './routes/_authenticated/wardrobe'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedBabyRouteImport } from './routes/_authenticated/baby'
import { Route as AuthenticatedOnboardingWardrobeRouteImport } from './routes/_authenticated/onboarding.wardrobe'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWardrobeRoute = AuthenticatedWardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBabyRoute = AuthenticatedBabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingWardrobeRoute =
  AuthenticatedOnboardingWardrobeRouteImport.update({
    id: '/onboarding/wardrobe',
    path: '/onboarding/wardrobe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baby': typeof AuthenticatedBabyRoute
  '/today': typeof AuthenticatedTodayRoute
  '/wardrobe': typeof AuthenticatedWardrobeRoute
  '/onboarding/wardrobe': typeof AuthenticatedOnboardingWardrobeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baby': typeof AuthenticatedBabyRoute
  '/today': typeof AuthenticatedTodayRoute
  '/wardrobe': typeof AuthenticatedWardrobeRoute
  '/onboarding/wardrobe': typeof AuthenticatedOnboardingWardrobeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/baby': typeof AuthenticatedBabyRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/wardrobe': typeof AuthenticatedWardrobeRoute
  '/_authenticated/onboarding/wardrobe': typeof AuthenticatedOnboardingWardrobeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/baby'
    | '/today'
    | '/wardrobe'
    | '/onboarding/wardrobe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/baby' | '/today' | '/wardrobe' | '/onboarding/wardrobe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/baby'
    | '/_authenticated/today'
    | '/_authenticated/wardrobe'
    | '/_authenticated/onboarding/wardrobe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wardrobe': {
      id: '/_authenticated/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof AuthenticatedWardrobeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baby': {
      id: '/_authenticated/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof AuthenticatedBabyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/wardrobe': {
      id: '/_authenticated/onboarding/wardrobe'
      path: '/onboarding/wardrobe'
      fullPath: '/onboarding/wardrobe'
      preLoaderRoute: typeof AuthenticatedOnboardingWardrobeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBabyRoute: typeof AuthenticatedBabyRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWardrobeRoute: typeof AuthenticatedWardrobeRoute
  AuthenticatedOnboardingWardrobeRoute: typeof AuthenticatedOnboardingWardrobeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBabyRoute: AuthenticatedBabyRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWardrobeRoute: AuthenticatedWardrobeRoute,
  AuthenticatedOnboardingWardrobeRoute: AuthenticatedOnboardingWardrobeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
